# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class CreateQuestion(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, question=None, question_type=None, answers=None):  # noqa: E501
        """CreateQuestion - a model defined in OpenAPI

        :param question: The question of this CreateQuestion.  # noqa: E501
        :type question: str
        :param question_type: The question_type of this CreateQuestion.  # noqa: E501
        :type question_type: str
        :param answers: The answers of this CreateQuestion.  # noqa: E501
        :type answers: str
        """
        self.openapi_types = {
            'question': str,
            'question_type': str,
            'answers': str
        }

        self.attribute_map = {
            'question': 'question',
            'question_type': 'question-type',
            'answers': 'answers'
        }

        self._question = question
        self._question_type = question_type
        self._answers = answers

    @classmethod
    def from_dict(cls, dikt) -> 'CreateQuestion':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CreateQuestion of this CreateQuestion.  # noqa: E501
        :rtype: CreateQuestion
        """
        return util.deserialize_model(dikt, cls)

    @property
    def question(self):
        """Gets the question of this CreateQuestion.


        :return: The question of this CreateQuestion.
        :rtype: str
        """
        return self._question

    @question.setter
    def question(self, question):
        """Sets the question of this CreateQuestion.


        :param question: The question of this CreateQuestion.
        :type question: str
        """
        if question is None:
            raise ValueError("Invalid value for `question`, must not be `None`")  # noqa: E501

        self._question = question

    @property
    def question_type(self):
        """Gets the question_type of this CreateQuestion.


        :return: The question_type of this CreateQuestion.
        :rtype: str
        """
        return self._question_type

    @question_type.setter
    def question_type(self, question_type):
        """Sets the question_type of this CreateQuestion.


        :param question_type: The question_type of this CreateQuestion.
        :type question_type: str
        """
        if question_type is None:
            raise ValueError("Invalid value for `question_type`, must not be `None`")  # noqa: E501

        self._question_type = question_type

    @property
    def answers(self):
        """Gets the answers of this CreateQuestion.


        :return: The answers of this CreateQuestion.
        :rtype: str
        """
        return self._answers

    @answers.setter
    def answers(self, answers):
        """Sets the answers of this CreateQuestion.


        :param answers: The answers of this CreateQuestion.
        :type answers: str
        """
        if answers is None:
            raise ValueError("Invalid value for `answers`, must not be `None`")  # noqa: E501

        self._answers = answers
