# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.question import Question
from openapi_server import util

from openapi_server.models.question import Question  # noqa: E501

class Questions(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, prev=None, next=None, items=None):  # noqa: E501
        """Questions - a model defined in OpenAPI

        :param prev: The prev of this Questions.  # noqa: E501
        :type prev: str
        :param next: The next of this Questions.  # noqa: E501
        :type next: str
        :param items: The items of this Questions.  # noqa: E501
        :type items: List[Question]
        """
        self.openapi_types = {
            'prev': str,
            'next': str,
            'items': List[Question]
        }

        self.attribute_map = {
            'prev': 'prev',
            'next': 'next',
            'items': 'items'
        }

        self._prev = prev
        self._next = next
        self._items = items

    @classmethod
    def from_dict(cls, dikt) -> 'Questions':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Questions of this Questions.  # noqa: E501
        :rtype: Questions
        """
        return util.deserialize_model(dikt, cls)

    @property
    def prev(self):
        """Gets the prev of this Questions.


        :return: The prev of this Questions.
        :rtype: str
        """
        return self._prev

    @prev.setter
    def prev(self, prev):
        """Sets the prev of this Questions.


        :param prev: The prev of this Questions.
        :type prev: str
        """

        self._prev = prev

    @property
    def next(self):
        """Gets the next of this Questions.


        :return: The next of this Questions.
        :rtype: str
        """
        return self._next

    @next.setter
    def next(self, next):
        """Sets the next of this Questions.


        :param next: The next of this Questions.
        :type next: str
        """

        self._next = next

    @property
    def items(self):
        """Gets the items of this Questions.


        :return: The items of this Questions.
        :rtype: List[Question]
        """
        return self._items

    @items.setter
    def items(self, items):
        """Sets the items of this Questions.


        :param items: The items of this Questions.
        :type items: List[Question]
        """

        self._items = items
